title: willion 的博客
description: 记录技术、生活与思考
url: "https://willion-47.github.io"
baseurl: ""

lang: zh-CN
timezone: Asia/Shanghai

theme: minima

header_pages:
  - about.md

permalink: /:year/:month/:day/:title/
